language: elixir
elixir:
    - 1.3.4
services:
    - postgresql
env:
    - NODE_VERSION="7.3.0"
before_install:
    - nvm install $NODE_VERSION
install:
    - cd $TRAVIS_BUILD_DIR/delicious_elixir && mix local.hex --force
    - cd $TRAVIS_BUILD_DIR/delicious_elixir && mix deps.get
    - cd $TRAVIS_BUILD_DIR/frontend && npm install
before_script:
    - psql -c 'create database postgres_test;' -U postgres
script:
    - cd $TRAVIS_BUILD_DIR/delicious_elixir && mix test
    - cd $TRAVIS_BUILD_DIR/frontend && npm run test
