language: elixir
elixir:
    - 1.3.4
services:
    - postgresql
env:
    - NODE_VERSION="7.3.0"
before_install:
    - nvm install $NODE_VERSION
install:
    - cd delicious_elixir && mix local.hex --force && mix deps.get && cd ..
    - cd frontend && npm install && cd ..
before_script:
    - psql -c 'create database postgres_test;' -U postgres
script:
    - cd delicious_elixir && mix test
    - cd frontend && npm run test
