language: elixir
elixir:
    - 1.3.4
services:
    - docker
before_install:
    - cp docker/config/db.example.env docker/config/db.env
    - docker-compose up
install:
    - cd ./delicious_elixir
    - mix local.hex --force
    - mix deps.get
script:
    - mix test
