version: '2'
services:
    db:
        image: postgres:9.5
        ports:
            - "5436:5432"
        volumes:
            - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
            - "./docker/files/shared:/shared:rw"
        env_file: ./docker/config/db.env
