version: '2'
services:
    db:
        image: postgres:9.5
        ports:
            - "5433:5432"
        volumes:
            - "./files/db-dumps/:/docker-entrypoint-initdb.d/"
            - "./files/shared:/shared:rw"
        env_file: ./config/db.env
